[project]
name = "research-inc-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.3",
    "sse-starlette>=2.2.1",
    "uvicorn>=0.34.0",
]
